### ISSUE TITLE
Why Commodore basic cannot run?

### ISSUE THREAD

**Issue by daitangio** [irmen/pyc64#5]
@irmen  What are the issue with the original commodore basic? What changed are needed to get it running using the 6502 emulator integrated inside pyc64?

**Comment by irmen** [comment]
Interesting question.
The main issue is the fact that pyc64 doesn't emulate all c64 hardware.  I think that we need at least one CIA chip emulation (for system timers) and ofcourse the keyboard.
Also, pyc64 currently runs "its own" main loop that deals with input and output. This has to be switched around to just run the c64's own rom routines via the 6502 emulator.

Also, I think it needs a proper ROM/RAM setup and bank switching perhaps (using the $00/$01 locations) because it's going to validate the machine's configuration to set up things such as bottom/top of basic ram memory and the like.  I could be wrong here though, I have no idea how the rom is actually initializing the system.

**Comment by irmen** [comment]
@daitangio You may be interested in my other project, Ksim65, that now actually includes a working commodore-64 emulator that runs the actual ROMS.

**Comment by irmen** [comment]
@daitangio have a look at this :

```
using actual ROM reset routine at 64738
CPU simulator: PC=$e5cf A=$00 X=$00 Y=$0a P=%00110010 -  clockspeed = 0.8 MHz   
```
yeah, I'm trying to get the real roms running in this Python simulator now as well, and I'm pretty amazed that it is currently running at almost real time in just regular python on my machine. This is not sustainable though because it's not doing all the work needed such as IRQ processing, but we can fix that by simply running the thing in pypy.  Which yields amazing results btw

**Comment by irmen** [comment]
Right, that was that :grin:  We've got a real C64 emulator in Python now! 
It runs the actual ROMs and you can type any BASIC program you like as on the original C64 :)

I/O is not emulated so you can't load or save your programs.

Start the 'true' emulator with the ``startreal64.py`` script.
